# Generated by Django 3.2.4 on 2021-07-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idautor', models.IntegerField(primary_key=True, serialize=False, verbose_name='idautor')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre autor')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('img', models.ImageField(null=True, upload_to='autores')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idobra', models.IntegerField(primary_key=True, serialize=False, verbose_name='idobra')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre obra')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('img', models.ImageField(null=True, upload_to='obras')),
                ('precio', models.IntegerField(default=0, verbose_name='precio')),
                ('fecha', models.IntegerField(default=0, verbose_name='anno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
    ]
