# Generated by Django 3.2.4 on 2021-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='precio'),
        ),
    ]
