# Generated by Django 3.2.4 on 2021-07-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='idcategoria')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre categoria')),
            ],
        ),
    ]
