# Generated by Django 3.2.4 on 2021-07-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210711_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha',
            field=models.IntegerField(default=0, verbose_name='anno'),
        ),
    ]
